file(READ "${VIDEO_OUTPUT}" VIDEO_OUTPUT_CONTENT)
function(extract_callback START_MARKER END_MARKER OUTPUT_VARIABLE)
  string(FIND "${VIDEO_OUTPUT_CONTENT}" "${START_MARKER}" START_POSITION)
  if(START_POSITION EQUAL -1)
    message(FATAL_ERROR "Missing callback: ${START_MARKER}")
  endif()
  string(SUBSTRING "${VIDEO_OUTPUT_CONTENT}" ${START_POSITION} -1 CALLBACK_TAIL)
  string(FIND "${CALLBACK_TAIL}" "${END_MARKER}" END_POSITION)
  if(END_POSITION EQUAL -1)
    message(FATAL_ERROR "Missing callback end")
  endif()
  string(LENGTH "${END_MARKER}" END_LENGTH)
  math(EXPR CALLBACK_LENGTH "${END_POSITION} + ${END_LENGTH}")
  string(SUBSTRING "${CALLBACK_TAIL}" 0 ${CALLBACK_LENGTH} CALLBACK)
  set(${OUTPUT_VARIABLE} "${CALLBACK}" PARENT_SCOPE)
endfunction()

extract_callback("[&, descriptor = texture.get()]" "\n            }" GPU_CALLBACK)
extract_callback("[&, descriptor = pixel_buffer_texture.get()]" "\n        }" SOFTWARE_CALLBACK)
configure_file("${CMAKE_CURRENT_LIST_DIR}/texture_callback_test.cpp.in"
  "${TEST_SOURCE}" @ONLY)
