# Run after configuration with -DVIDEO_OUTPUT=<generated source> -P this file.
file(READ "${VIDEO_OUTPUT}" VIDEO_OUTPUT_CONTENT)
foreach(NUMERATOR width height)
  string(REGEX MATCH "return ${NUMERATOR} [^;]+SW_RENDERING_MAX_[^;]+;"
    RETURN_STATEMENT "${VIDEO_OUTPUT_CONTENT}")
  if(NOT RETURN_STATEMENT)
    message(FATAL_ERROR "Missing ${NUMERATOR} scaling expression")
  endif()
  string(REGEX REPLACE "^return (.*);$" "\\1" EXPRESSION "${RETURN_STATEMENT}")
  if(NUMERATOR STREQUAL "width")
    set(VIDEO_WIDTH 1080)
    set(VIDEO_HEIGHT 1920)
    set(EXPECTED 607)
  else()
    set(VIDEO_WIDTH 2560)
    set(VIDEO_HEIGHT 720)
    set(EXPECTED 540)
  endif()
  string(REPLACE "SW_RENDERING_MAX_WIDTH" "1920" EXPRESSION "${EXPRESSION}")
  string(REPLACE "SW_RENDERING_MAX_HEIGHT" "1080" EXPRESSION "${EXPRESSION}")
  string(REPLACE "width" "${VIDEO_WIDTH}" EXPRESSION "${EXPRESSION}")
  string(REPLACE "height" "${VIDEO_HEIGHT}" EXPRESSION "${EXPRESSION}")
  math(EXPR ACTUAL "${EXPRESSION}")
  if(NOT ACTUAL EQUAL EXPECTED)
    message(FATAL_ERROR "${VIDEO_WIDTH}x${VIDEO_HEIGHT}: ${NUMERATOR}=${ACTUAL}, expected ${EXPECTED}")
  endif()
  message(STATUS "${VIDEO_WIDTH}x${VIDEO_HEIGHT}: scaled ${NUMERATOR}=${ACTUAL}")
endforeach()
